compiler: G:\steam\steamapps\common\Skyrim Special Edition\Papyrus Compiler\PapyrusCompiler.exe
flags: TESV_Papyrus_Flags.flg
output: E:\Infernio\Desktop\Programming\Skyrim\MLib\scripts
imports:
    - E:\Infernio\Desktop\Programming\Skyrim\MLib\scripts\source
    - G:\Steam\steamapps\common\Skyrim Special Edition\Data\Scripts\Source
optimize: true
