compiler: D:\Steam\steamapps\common\Skyrim\Papyrus Compiler\PapyrusCompiler.exe
flags: TESV_Papyrus_Flags.flg
output: D:\Users\Infernio\Desktop\Programming\Skyrim\MLib\scripts
imports:
    - D:\Users\Infernio\Desktop\Programming\Skyrim\MLib\scripts\source
    - D:\Steam\steamapps\common\Skyrim\Data\Scripts\Source
    - D:\Steam\steamapps\common\Skyrim\Data\Scripts
optimize: true
